kraken_wl_sizes:
  - k: 21
    l: 14
  - k: 27
    l: 18
  - k: 35
    l: 31

kraken_db_size:
  - "full"
  - "10gb"

containers:
  kraken: "docker://quay.io/mbhall88/kraken2:84e851b"
  tb_decontam: "docker://quay.io/mbhall88/tb-decontam:0.1.1"
  base: "docker://bash:5.1"
  python: "docker://python:3.10.4-slim-bullseye"
  spumoni: "docker://quay.io/mbhall88/spumoni:2.0.7"
  minimap2: "docker://quay.io/biocontainers/minimap2:2.26--he4a0461_1"
  pysam: "docker://quay.io/biocontainers/pysam:0.21.0--py310h41dec4a_1"
  samtools: "docker://quay.io/biocontainers/samtools:1.17--hd87286a_1"
  badread: "docker://quay.io/biocontainers/badread:0.4.0--pyhdfd78af_1"
  rs_utils: "docker://quay.io/mbhall88/rs-utils:0.1.0"
  sra_human_scrubber: "docker://ncbi/sra-human-scrubber:2.1.0"

ancestral_genome:
  url: "https://zenodo.org/record/3497110/files/MTB_ancestor_reference.fasta"
  md5: "4814ac17284bca12f95ad2c77daed4e5"

mtb_gramtools:
  url: "https://zenodo.org/record/5075458/files/4_mtb_validation_assemblies.tar"
  md5: "658fcdd15c4364c4111cb89d15b24c50"

gramtools_lineages: "config/mtb_gramtools_lineages.csv"

simulate:
  quantity: "5G"
  proportions:
    Unmapped: 0.11
    Human: 0.41
    Virus: 0.01
    Bacteria: 0.41
    NTM: 0.01
    MTBC: 0.05