kraken_wl_sizes:
  - k: 35
    l: 31
#  - k: 21
#    l: 14
#  - k: 27
#    l: 18

benchmark_repeats: 10

containers:
  kraken: "docker://quay.io/mbhall88/kraken2:84e851b"
  tb_decontam: "docker://quay.io/mbhall88/tb-decontam:0.1.1"
  base: "docker://bash:5.1"
  python: "docker://python:3.10.4-slim-bullseye"
  minimap2: "docker://quay.io/biocontainers/minimap2:2.26--he4a0461_1"
  pysam: "docker://quay.io/biocontainers/pysam:0.21.0--py310h41dec4a_1"
  samtools: "docker://quay.io/biocontainers/samtools:1.17--hd87286a_1"
  badread: "docker://quay.io/biocontainers/badread:0.4.0--pyhdfd78af_1"
  rs_utils: "docker://quay.io/mbhall88/rs-utils:0.1.0"
  sra_human_scrubber: "docker://ncbi/sra-human-scrubber:2.1.0"
  seqtk: "docker://quay.io/biocontainers/seqtk:1.4--he4a0461_1"
  hostile: "docker://quay.io/biocontainers/hostile:0.0.3--pyhdfd78af_0"
  genome_updater: "docker://quay.io/biocontainers/genome_updater:0.6.3--hdfd78af_0"
  mashtree: "docker://quay.io/biocontainers/mashtree:1.2.0--pl5321h031d066_2"
  drep: "docker://quay.io/biocontainers/drep:3.4.3--pyhdfd78af_0"
  seqkit: "docker://quay.io/biocontainers/seqkit:2.5.1--h9ee0642_0"
  fastq_dl: "docker://quay.io/biocontainers/fastq-dl:2.0.4--pyhdfd78af_0"

ancestral_genome:
  url: "https://zenodo.org/record/3497110/files/MTB_ancestor_reference.fasta"
  md5: "4814ac17284bca12f95ad2c77daed4e5"

mtb_gramtools:
  url: "https://zenodo.org/record/5075458/files/4_mtb_validation_assemblies.tar"
  md5: "658fcdd15c4364c4111cb89d15b24c50"

gramtools_lineages: "config/mtb_gramtools_lineages.csv"

simulate:
  quantity: "5G"
  proportions:
    Unmapped: 0.11
    Human: 0.41
    Virus: 0.01
    Bacteria: 0.41
    NTM: 0.01
    MTBC: 0.05

# ========== REAL DATA METADATA ==========

# HG00277
# Finnish

# ONT reads: https://s3.amazonaws.com/1000g-ont/100_PLUS/unaligned_bams/HG00277.LSK114.R10.dorado034.sup.5mCG_5hmCG.all.unaligned.bam
# Illumina: ERR3241786  NovaSeq 6000

# HG04054
# Indian Telugu in the UK

# ONT reads: https://s3.amazonaws.com/1000g-ont/UltraLong/unaligned_bams/HG04054.ULK114.R10.dorado034.sup.5mCG_5hmCG.all.unaligned.notPhased.bam
# Illumina: ERR3243120  NovaSeq 6000

# NA19318
# Luhya, Kenya

# POD5: https://s3.amazonaws.com/1000g-ont/pod5_data/GM19318-ONT-WGS-LSK114-01.tar 681GB
# https://s3.amazonaws.com/1000g-ont/pod5_data/GM19318-ONT-WGS-LSK114-02.tar 539GB
# https://s3.amazonaws.com/1000g-ont/pod5_data/GM19318-ONT-WGS-LSK114-03.tar 502GB
# Illumina: ERR3239713 NovaSeq 6000

# HG03611
# Bengali, Bangladesh

# POD5: https://s3.amazonaws.com/1000g-ont/pod5_data/NU_HG03611_ONT-WGS-ULK114.tar 896.3
# Illumina: ERR3243073 NovaSeq 6000

real_data:
  mtb:  # https://doi.org/10.1093/bib/bbac256
    ont: ERR8170871  # sample S3 R10.3
    illumina: ERR245682  # sample S3 HiSeq 4000
  zymo:  # https://www.nature.com/articles/s41592-022-01539-7
    ont: ERR7287988  # zymo mock community ZymoBIOMICS HMW DNA Standard (D6322) R10.4
    illumina: ERR7255689  # MiSeq
  # human:
  #   HG00277:  # Finnish
  #     ont: "https://s3.amazonaws.com/1000g-ont/100_PLUS/unaligned_bams/HG00277.LSK114.R10.dorado034.sup.5mCG_5hmCG.all.unaligned.bam"
  #     illumina: ERR3241786
  #   NA19318:  # Luhya, Kenya
  #     ont: "https://s3.amazonaws.com/1000g-ont/pod5_data/GM19318-ONT-WGS-LSK114-01.tar"
  #     illumina: ERR3239713
  #   HG03611:  # Bengali, Bangladesh
  #     ont: "https://s3.amazonaws.com/1000g-ont/pod5_data/NU_HG03611_ONT-WGS-ULK114.tar"
  #     illumina: ERR3243073

max_real_bases: "3G"