kraken_wl_sizes:
  - k: 21
    l: 14
  - k: 27
    l: 18
  - k: 35
    l: 31

kraken_db_size:
  - "full"
  - "10gb"

containers:
  kraken: "docker://quay.io/mbhall88/kraken2:84e851b"
  tb_decontam: "docker://quay.io/mbhall88/tb-decontam:0.1.1"
  base: "docker://bash:5.1"
  python: "docker://python:3.10.4-slim-bullseye"
  spumoni: "docker://quay.io/mbhall88/spumoni:2.0.7"
  minimap2: "docker://quay.io/biocontainers/minimap2:2.26--he4a0461_1"

ancestral_genome:
  url: "https://zenodo.org/record/3497110/files/MTB_ancestor_reference.fasta"
  md5: "4814ac17284bca12f95ad2c77daed4e5"

mtb_gramtools:
  url: "https://zenodo.org/record/5075458/files/4_mtb_validation_assemblies.tar"
  md5: "658fcdd15c4364c4111cb89d15b24c50"

gramtools_lineages: "config/mtb_gramtools_lineages.csv"